travis:
  secure:
    BINSTAR_TOKEN: PEDWQEZf6fs+Gm7qXGmK2AqHkdpWdcWa/18X7qVBlOOaXDZjCjGmjh3p1Ud/rhWyu4irrbKbxHZPM6v4wyIcXYdO6tBQqUnQjs9VX3jVColLwkMWnoDpwE4Z1F25iL8kcYY1Fk1MjawWkafRunY37ta+6kiCrSh52M615MtYiEw+pR5Nkcbr94/gBBpqeu5uNyMtqPOm+z/ExrlRUSrcbxShJoX2aEpFjFWhZ2hadarZ+hcGmdnqNZ71JTx8UVHIoWqXOfximjU6dPHgQQcqdb3HrOvA+eHApLG4Jr5hv/6xTxAq0vqQR+YawU3ywFwXH66fXjJo0V8X+4oOIzlLXVfYvsIVbKKRs7yvQ55QbURYh+WSSFxWRmHIbStjpkX57p7JUepTEjIeznreKJKQToGMcKCXhh0HGoGdIptQKqyElKwKQ9Yj3DH76q5knoWT9pOeAv4F+KOotNVR+9Ar4JsPWCppKOSUR/hoSB8/MqPqFUWU1ObdjNh9SP6WjF3Ap6WN0LKtBqMWqreP6eUfdn2zXCd7iSq95ZxUhDINpc4ze7XaGAbRfD3bivXU2rDcxjiMhPEl+nQ5Z5JUyCLsRh6HL0I7A/lPPByzsAdiHHFJmPVW1paPnx70UPG00nnsIgX7CULo/bPiQ2IpzufZKF/5ZnfTTAXVpgBHsfF1DhY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: appveyor
